# Generated by Django 4.2.20 on 2025-04-10 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('department', models.CharField(max_length=10)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(70), django.core.validators.MinValueValidator(25)])),
            ],
        ),
    ]
