# Generated by Django 4.2.20 on 2025-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='staff_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
