# Generated by Django 4.2.20 on 2025-04-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_leaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('cl_avail', models.IntegerField()),
                ('cl_used', models.IntegerField()),
                ('el_avail', models.IntegerField()),
                ('el_used', models.IntegerField()),
                ('sl_avail', models.IntegerField()),
                ('sl_used', models.IntegerField()),
            ],
        ),
    ]
